"""Add price_per_hour to parking_lot

Revision ID: 6bc25cb4349f
Revises: 31609246f581
Create Date: 2025-07-29 21:52:54.916723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc25cb4349f'
down_revision = '31609246f581'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('parking_lot', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('price_per_hour', sa.Float(), nullable=False, server_default='0'))
        batch_op.drop_column('price')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_lot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False, server_default='0'))
        batch_op.drop_column('price_per_hour')

    # ### end Alembic commands ###
