"""Make end_time nullable

Revision ID: cddd4ecf9bae
Revises: 6bc25cb4349f
Create Date: 2025-07-30 07:05:25.805287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cddd4ecf9bae'
down_revision = '6bc25cb4349f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text("'2025-01-01 00:00:00'"))
        batch_op.alter_column('end_time',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text("'2025-01-01 01:00:00'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text("'2025-01-01 01:00:00'"))
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text("'2025-01-01 00:00:00'"))

    # ### end Alembic commands ###
